version: "3.9"
services:
  route-service:
    build: .
    ports:
      - "5003:5003"
    environment:
      - NEO4J_USER=${NEO4J_USER}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - NEO4J_URI=${NEO4J_URI}
